---
- name: install required packages
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - java-1.8.0-openjdk

- name: Check if we are done
  stat:
    path: "{{ keycloak_jboss_home }}/create.done"
  register: _done_file

- block:

  - name: create keycloak user
    user:
      name: keycloak

  - name: keycloak target directory
    file:
      dest: "{{ keycloak_dir }}"
      mode: 0755
      owner: root
      group: root
      state: directory

  - name: get Keycloak distribution tarball
    get_url:
      url: "{{ keycloak_url }}"
      dest: "{{ keycloak_dir }}"

  - name: unpack keycloak
    unarchive:
      src: "{{ keycloak_dir }}/{{ keycloak_archive }}"
      dest: "{{ keycloak_dir }}"
      copy: no

  - name: keycloak log directory
    file:
      dest: "{{ keycloak_log_dir }}"
      mode: 0755
      owner: keycloak
      group: keycloak
      state: directory

  - name: keycloak systemd setup
    template:
      owner: root
      group: root
      mode: 0644
      src: keycloak.service.j2
      dest: /etc/systemd/system/keycloak.service

  - name: start keycloak
    systemd:
      name: keycloak
      state: start
      enabled: yes


